server:
  port: 8762

spring:
  application:
    name: lagou-cloud-eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: LagouCloudEurekaServerB
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@